import './globals.css';

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ChatCPE",
  description: "Generated by create next app, this is a simple screening bot for " +
      "answering questions about CPE department.",
};

/**
 * RootLayout - A component that renders the root layout of the application.
 *
 * @param {Object} props - The component props.
 * @param {React.ReactNode} props.children - The child elements to be rendered inside the root layout.
 * @return {JSX.Element} The root layout JSX element.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}


